# Generated by Django 5.0.3 on 2026-03-08 12:24

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Base Price (€)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Bot Category',
                'verbose_name_plural': 'Bot Categories',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Order ID')),
                ('requirements_json', models.JSONField(blank=True, default=dict, verbose_name='AI Generated Requirements')),
                ('consulting_requested', models.BooleanField(default=False, verbose_name='Consulting Upsell Selected')),
                ('contact_info', models.CharField(blank=True, max_length=255, verbose_name='Contact Information')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Price (€)')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid & Drafted'), ('in_progress', 'Development In Progress'), ('delivered', 'Delivered')], default='pending', max_length=20, verbose_name='Status')),
                ('draft_file_path', models.CharField(blank=True, max_length=255, verbose_name='Draft File Path')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.botcategory', verbose_name='Bot Category')),
            ],
            options={
                'verbose_name': 'Bot Order',
                'verbose_name_plural': 'Bot Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='bots.botcategory')),
            ],
            options={
                'verbose_name': 'Bot Category Translation',
                'db_table': 'bots_botcategory_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
