# Generated by Django 5.0.3 on 2026-03-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_order_is_active_order_user_botadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_hosted',
            field=models.BooleanField(default=True, verbose_name='Managed Hosting'),
        ),
        migrations.AddField(
            model_name='order',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Monthly Hosting Fee (€)'),
        ),
        migrations.AddField(
            model_name='order',
            name='source_code_url',
            field=models.CharField(blank=True, help_text='Link to the clean source code for non-hosted bots', max_length=500, verbose_name='Source Code URL/Path'),
        ),
    ]
