# Generated by Django 5.0.3 on 2026-03-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_order_is_hosted_order_monthly_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='IP Address')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Session Key')),
                ('message_count', models.IntegerField(default=0, verbose_name='Message Count')),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rate Limit Tracker',
                'verbose_name_plural': 'Rate Limit Trackers',
            },
        ),
    ]
