version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=bot_butler_db
      - POSTGRES_USER=bot_butler_user
      - POSTGRES_PASSWORD=bot_butler_pass
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - bot_drafts:/var/bot_drafts
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
  static_volume:
  media_volume:
  bot_drafts:
