# Generated by Django 5.0.3 on 2026-03-10 13:02

import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/images/', verbose_name='Featured Image (OG)')),
                ('author', models.CharField(default='Admin', max_length=100, verbose_name='Author')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_indexable', models.BooleanField(default=True, help_text='Allow search engines to index this post. Uncheck to add noindex tag.', verbose_name='Indexable (SEO)')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BlogPostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('slug', models.SlugField(help_text='URL identifier for this language', max_length=255, unique=True, verbose_name='Slug')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (SEO)')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description (SEO)')),
                ('keywords', models.CharField(blank=True, help_text='Comma separated keywords', max_length=500, verbose_name='Keywords (SEO)')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Accessibility and Image SEO describing the featured image', max_length=200, verbose_name='Image Alt Text (SEO)')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Post Translation',
                'db_table': 'blog_blogpost_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
