upstream bot_butler_upstream {
    server bot_butler-web-1:8000;
}

server {
    listen 80;
    server_name bot-butler.ai www.bot-butler.ai;

    client_max_body_size 20M;

    location / {
        proxy_pass http://bot_butler_upstream;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }

    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
    }

    location /media/ {
        alias /app/media/;
    }
}
